server {
    listen 80 default_server;
    server_name _;

    location = / {
        return 302 /ball/;
    }

    location /ball/ {
        alias /usr/share/nginx/html/ball/;
        index index.html;
        try_files $uri $uri/ /ball/index.html;
    }
}
